esphome:
  name: acunit

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Acunit Fallback Hotspot"
    password: !secret wifi_password

  on_disconnect:
    - switch.turn_off: ac_on_off

external_components:
  # use all components from a local folder
  - source:
      type: local
      path: my_components

switch:
  - platform: ac_switch
    name: AC Switch
    id: ac_on_off
    pin: D2
    uart_id: uart_display

climate:
  - platform: ac_climate
    name: Air Conditioner
    id: ac_climate_device
    pin: D2
    uart_id: uart_display

# So the rate and bit count probably is wrong, but from this at the least I can tell what state the unit is in.. or maybe its the endianness? Either way.
uart:
  tx_pin: 0
  rx_pin:
    number: D5
    inverted: false
  rx_buffer_size: 64
  data_bits: 6 # 6
  parity: NONE
  stop_bits: 1 # 1
  baud_rate: 2000 # 2000
  id: uart_display
  debug: